icons_format = "{icon}"

[theme]
theme = "tokyonight_night"
#[theme.overrides]
#alternating_tint_bg = "#15161e"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
format = "$icon $path $free "
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
format = "$path $free "
path = "/home"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:2) "
format_alt = "$icon $mem_used/$mem_total "
warning_mem = 75.0
critical_mem = 90.0
warning_swap = 90.0
critical_swap = 95.0
interval = 10
[[block.click]]
button = "left"
cmd = "alacritty -e btm"
[[block.click]]
button = "right"
action = "toggle_format"

[[block]]
block = "cpu"
format = "$icon $utilization "
format_alt = "$icon $utilization $barchart "
interval = 10
[[block.click]]
button = "left"
cmd = "alacritty -e btm"
[[block.click]]
button = "right"
action = "toggle_format"

#[[block]]
#block = "watson"
#show_time = false
#state_path = "~/.config/watson/state"

#[[block]]
#block = "taskwarrior"
#interval = 60
#format = " $icon $count.eng(w:1) tasks "
#format_singular = " $icon 1 task "
#format_everything_done = ""
#warning_threshold = 20
#critical_threshold = 30

#[[block]]
#block = "music"
#player = "spotify"
#format = " $icon $combo.str(max_w:16) |"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "D4:68:AA:7A:36:13" # AirPods
disconnected_format = "$icon "
format = "$icon "
[block.battery_state]
"0..20" = "critical"
"21..50" = "warning"
"51..100" = "good"

[[block]]
block = "bluetooth"
mac = "78:2B:64:CC:CB:AC" # Bose
disconnected_format = ""
format = "$icon "
[block.battery_state]
"0..20" = "critical"
"21..50" = "warning"
"51..100" = "good"

[[block]]
block = "net"
format = "$icon {$signal_strength|} "
format_alt = "$icon {$ssid ($frequency) $signal_strength - |}$ip "
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"
[[block.click]]
button = "right"
action = "toggle_format"

[[block]]
block = "weather"
format = "$icon $weather $temp "
service = { name = "openweathermap", city_id = "2657896", units = "metric" }
autolocate = true

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%a %e. %b %R') "

[[block]]
block = "battery"
interval = 30
format = "$icon $percentage "
full_format = "$icon $percentage "
empty_format = "$icon $percentage "

#[[block]]
#block = "toggle"
#format = " $icon 4k "
#command_state = "xrandr | grep 'DisplayPort-0 connected 38'"
#command_on = "xrandr --output eDP --auto --primary --output DisplayPort-0 --auto --right-of \"eDP\""
#command_off = "xrandr --auto"
#interval = 5

[[block]]
block = "custom"
cycle = ["nmcli n on && echo '{\"icon\":\"\",\"state\":\"Idle\",\"text\":\"\U000f001d\"}'",
		 "nmcli n off && echo '{\"icon\":\"\",\"state\":\"Warning\",\"text\":\"\U000f187b\"}'"]
json = true

[[block]]
block = "pacman"
interval = 600
format = "$icon $pacman updates available "
format_singular = "$icon $pacman update available "
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
[[block.click]]
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs/ | rofi -dmenu"
[[block.click]]
button = "right"
update = true

#[[block]]
#block = "keyboard_layout"
#driver = "setxkbmap"
#interval = 15

[[block]]
block = "menu"
text = "\uf011 "
[[block.items]]
display = " Sleep "
cmd = "systemctl suspend"
[[block.items]]
display = " Shutdown "
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " Reboot "
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
