idle_bg = "#1C1B19"
idle_fg = "#FCE8C3"
info_bg = "#1C1B19"
info_fg = "#68A8E4"
good_bg = "#1C1B19"
good_fg = "#98BC37"
warning_bg = "#1C1B19"
warning_fg = "#FBB829"
critical_bg = "#1C1B19"
critical_fg = "#F75341"
separator = " "
separator_bg = "auto"
separator_fg = "auto"
