idle_bg = "#1C1B19"
idle_fg = "#FCE8C3"
info_bg = "#68A8E4"
info_fg = "#1C1B19"
good_bg = "#98BC37"
good_fg = "#1C1B19"
warning_bg = "#FF8700"
warning_fg = "#1C1B19"
critical_bg = "#F75341"
critical_fg = "#1C1B19"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
