idle_bg = "#1a1b26"
idle_fg = "#c0caf5"
info_bg = "#7aa2f7"
info_fg = "#1a1b26"
good_bg = "#9ece6a"
good_fg = "#1a1b26"
warning_bg = "#e0af68"
warning_fg = "#1a1b26"
critical_bg = "#f7768e"
critical_fg = "#1a1b26"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
